### ISSUE TITLE
Request for License Information

### ISSUE THREAD

**Issue by ehaupt** [kost/revsocks#9]
Could you kindly provide information regarding the license of your project?

**Comment by kost** [comment]
Fixed in 0503e24b3f1acc3153360828b70d1084da657759 

BTW it is MIT License.

**Comment by ehaupt** [comment]
Thank you @kost for clarifying. I've packaged the latest version for [FreeBSD](https://repology.org/project/revsocks/packages). Maybe some other packagers will follow.

BTW, there are some nice repology badges: https://repology.org/project/revsocks/badges
